[package]
name = "zefirs-flashy-cooler"
version = "0.0.3"
description = "Backend handlers for Zefir's Flashy Cooler"
authors = ["Bruno St. John"]
license = "Apache-2.0"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hidapi = "2.2.0"
base64 = "0.21.0"

[dependencies.neon]
version = "0.10"
default-features = false
features = ["napi-6"]
