[package]
name = "librehardwaremonitor-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
librehardwaremonitor-sys = { path = "../librehardwaremonitor-sys" }
thiserror = "1.0.50"

[build-dependencies]
dotnetaot-build = {path="../dotnetaot-build"}