[package]
name = "smol-static"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
async-compression = { version = "0.4.5", features = ["tokio", "gzip"] }
mime_guess = "2.0.4"
tachyonix = "0.2.1"
tokio = { version = "1.35.0", features = ["full"] }
