name: Check code quality

on:
  pull_request:
  push:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - ".vscode/**"
      - "LICENSE"
      - ".github/**"

jobs:
  Frontend-Quality:
    name: Frontend code quality
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout 🛎️

      - uses: actions/setup-node@v3
        name: Setup Node ⚙️
        with:
          node-version: 18

      - name: Install dependencies 🏗️
        run: npm install

      - name: Check code quality 🔩
        run: npm run lint

  Rust-Quality:
    name: Rust code quality
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout 🛎️

      - uses: actions-rs/toolchain@v1
        name: Install Rust toolchain ☄️
        with:
          toolchain: stable

      - uses: davidB/rust-cargo-make@v1
        name: Install cargo-make ⌨️

      - uses: reinismu/clippy-check@master
        name: Check code quality 📑
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
          working-directory: src-tauri
