name: Generate sponsors section in readme
permissions:
  contents: write
on:
  workflow_dispatch:
  schedule:
    - cron: 30 15 * * 0-6
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Generate Sponsors 💖
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.GHA_README_SPONSORS }}
          file: "README.md"

      - name: Deploy to GitHub 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: "."
          token: ${{ secrets.GHA_README_SPONSORS }}
          commit-message: "chore: update sponsors"
