name: Test code

on:
  pull_request:
  push:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - ".vscode/**"
      - "LICENSE"
      - ".github/**"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout 🛎️

      - uses: actions/setup-node@v3
        name: Setup Node ⚙️
        with:
          node-version: 18

      - name: Install frontend dependencies 🏗️
        run: npm install

      - name: Run frontend tests 🧫
        run: npm test

      - uses: actions-rs/toolchain@v1
        name: Install Rust toolchain ☄️
        with:
          toolchain: stable

      - uses: davidB/rust-cargo-make@v1
        name: Install cargo-make ⌨️

      - name: Run Rust code tests 🧪
        working-directory: src-tauri
        run: cargo make tests
